# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6639236490d75a9d31d5391bc5304f9302e37dde72fcb6be44f07d2e97773b028fc6c21ebc148647d99522b45592b3f79fb73e13a212370f761d5df943489794

test:
  secret_key_base: 8d576de13ccf1df49148f5136c9f29318a02a5f477f7d15f7cbf25173423ccc4ff99e438a6b956c1466ee61f50cbe567a70f832a05cb96f9f19bd467a8a543b0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
